#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

i=1
for monitor in $(bspc query -M); do
bspc monitor $monitor \
        -n "$i" \
        -d I
    let i++
done

bspc config border_width         2.5
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bpsc rule -a android-studio desktop='^8' state=floating

bspc config normal_border_color "#89DDFF"
bspc config active_border_color "#C3E88D"
bspc config focused_border_color "#82AAFF"
bspc config presel_feedback_color "#C792EA"

# Startup command
setxkbmap us

brightnessctl s 10-

feh --bg-fill ~/Pictures/eric-jacob-G0miZ5OYaXI-unsplash.jpg

picom -f &

dunst &

$HOME/.config/polybar/launch.sh
