# Inserts a blank line between shell prompts
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[⊗](bold red)" # used if previous command failed

[cmd_duration]
format = "took [$duration](bold yellow) "
disabled = false
show_notifications = true   

# Nerd Font Symbols
# https://starship.rs/presets/nerd-font.html
[aws]
symbol = "  "

[buf]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[directory]
read_only = " "
truncation_length = 7
truncation_symbol = "…/"

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[rust]
symbol = " "

[username]
style_user = "bold purple"
style_root = "red bold"
format = "  [$user]($style) "
disabled = false
show_always = true
